
package sk.ditec.crdexp.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OutboundConnectorService", targetNamespace = "http://uic.cc.org/li/messageprocessing/outbound/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OutboundConnectorService {


    /**
     * 
     * @param parameters
     * @param encoded
     * @return
     *     returns sk.ditec.crdexp.ws.SendOutboundMessageResponse
     */
    @WebMethod(operationName = "SendOutboundMessage", action = "SendOutboundMessageAction")
    @WebResult(name = "SendOutboundMessageResponse", targetNamespace = "http://uic.cc.org/li/messageprocessing/outbound/", partName = "parameters")
    public SendOutboundMessageResponse sendOutboundMessage(
        @WebParam(name = "SendOutboundMessage", targetNamespace = "http://uic.cc.org/li/messageprocessing/outbound/", partName = "parameters")
        SendOutboundMessage parameters,
        @WebParam(name = "Encoded", targetNamespace = "http://uic.cc.org/li/messageprocessing/header", header = true, partName = "Encoded")
        boolean encoded);

}
