
package sk.ditec.crdexp.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OutboundConnectorService", targetNamespace = "http://uic.cc.org/li/messageprocessing/outbound/", wsdlLocation = "http://location01service-zsr-ipaas.apps.ocptest.intra.zsr.sk/service/location01service?wsdl")
public class OutboundConnectorService_Service
    extends Service
{

    private final static URL OUTBOUNDCONNECTORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(sk.ditec.crdexp.ws.OutboundConnectorService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = sk.ditec.crdexp.ws.OutboundConnectorService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://location01service-zsr-ipaas.apps.ocptest.intra.zsr.sk/service/location01service?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://location01service-zsr-ipaas.apps.ocptest.intra.zsr.sk/service/location01service?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OUTBOUNDCONNECTORSERVICE_WSDL_LOCATION = url;
    }

    public OutboundConnectorService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OutboundConnectorService_Service() {
        super(OUTBOUNDCONNECTORSERVICE_WSDL_LOCATION, new QName("http://uic.cc.org/li/messageprocessing/outbound/", "OutboundConnectorService"));
    }

    /**
     * 
     * @return
     *     returns OutboundConnectorService
     */
    @WebEndpoint(name = "OutboundConnectorServicePort")
    public OutboundConnectorService getOutboundConnectorServicePort() {
        return super.getPort(new QName("http://uic.cc.org/li/messageprocessing/outbound/", "OutboundConnectorServicePort"), OutboundConnectorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OutboundConnectorService
     */
    @WebEndpoint(name = "OutboundConnectorServicePort")
    public OutboundConnectorService getOutboundConnectorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uic.cc.org/li/messageprocessing/outbound/", "OutboundConnectorServicePort"), OutboundConnectorService.class, features);
    }

}
