torque.database.default = APP

torque.database.APP.adapter=oracle
torque.dsfactory.APP.factory=org.apache.torque.dsfactory.JndiDataSourceFactory
torque.dsfactory.APP.jndi.path=ditec__cud
torque.dsfactory.APP.connection.customizer = ALTER SESSION SET NLS_SORT\=SLOVAK_AI   
torque.dsfactory.APP.connection.timeout = 600
torque.dsfactory.APP.connection.stacktraces = true

torque.dsfactory.APP.connection.driver = net.sf.log4jdbc.DriverSpy
torque.dsfactory.APP.connection.url = jdbc:log4jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=kistest.intra.ditec.sk)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ssd.intra.ditec.sk)))
torque.dsfactory.APP.connection.user = cud
torque.dsfactory.APP.connection.password = cud
