
package sk.ditec.exp.rinfws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RinfDataWSService", targetNamespace = "urn:rinf.pis.ws.ditec.sk", wsdlLocation = "http://kistest/rinf/RinfDataWS?wsdl")
public class RinfDataWSService
    extends Service
{

    private final static URL RINFDATAWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException RINFDATAWSSERVICE_EXCEPTION;
    private final static QName RINFDATAWSSERVICE_QNAME = new QName("urn:rinf.pis.ws.ditec.sk", "RinfDataWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://kistest/rinf/RinfDataWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RINFDATAWSSERVICE_WSDL_LOCATION = url;
        RINFDATAWSSERVICE_EXCEPTION = e;
    }

    public RinfDataWSService() {
        super(__getWsdlLocation(), RINFDATAWSSERVICE_QNAME);
    }

    public RinfDataWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RINFDATAWSSERVICE_QNAME, features);
    }

    public RinfDataWSService(URL wsdlLocation) {
        super(wsdlLocation, RINFDATAWSSERVICE_QNAME);
    }

    public RinfDataWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RINFDATAWSSERVICE_QNAME, features);
    }

    public RinfDataWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RinfDataWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RinfDataWS
     */
    @WebEndpoint(name = "RinfDataWSPort")
    public RinfDataWS getRinfDataWSPort() {
        return super.getPort(new QName("urn:rinf.pis.ws.ditec.sk", "RinfDataWSPort"), RinfDataWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RinfDataWS
     */
    @WebEndpoint(name = "RinfDataWSPort")
    public RinfDataWS getRinfDataWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:rinf.pis.ws.ditec.sk", "RinfDataWSPort"), RinfDataWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RINFDATAWSSERVICE_EXCEPTION!= null) {
            throw RINFDATAWSSERVICE_EXCEPTION;
        }
        return RINFDATAWSSERVICE_WSDL_LOCATION;
    }

}
