
package sk.ditec.exp.rinfws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import sk.ditec.common.ws.AuthInfoWS;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RinfDataWS", targetNamespace = "urn:rinf.pis.ws.ditec.sk")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RinfDataWS {


    /**
     * 
     * @param opOd
     * @param authInfoWS
     * @param opDo
     * @return
     *     returns java.lang.String
     * @throws AppException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRinfDataServiceSol", targetNamespace = "urn:rinf.pis.ws.ditec.sk", className = "sk.ditec.exp.rinfws.GetRinfDataServiceSol")
    @ResponseWrapper(localName = "getRinfDataServiceSolResponse", targetNamespace = "urn:rinf.pis.ws.ditec.sk", className = "sk.ditec.exp.rinfws.GetRinfDataServiceSolResponse")
    @Action(input = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceSolRequest", output = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceSolResponse", fault = {
        @FaultAction(className = AppException.class, value = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceSol:Fault:AppException")
    })
    public String getRinfDataServiceSol(
        @WebParam(name = "AuthInfoWS", targetNamespace = "")
        AuthInfoWS authInfoWS,
        @WebParam(name = "OpOd", targetNamespace = "")
        String opOd,
        @WebParam(name = "OpDo", targetNamespace = "")
        String opDo)
        throws AppException
    ;

    /**
     * 
     * @param idCskmdOdOpDo
     * @param authInfoWS
     * @param idCskmdOdOpOd
     * @param cisloTu
     * @return
     *     returns java.lang.String
     * @throws AppException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRinfDataServiceTu", targetNamespace = "urn:rinf.pis.ws.ditec.sk", className = "sk.ditec.exp.rinfws.GetRinfDataServiceTu")
    @ResponseWrapper(localName = "getRinfDataServiceTuResponse", targetNamespace = "urn:rinf.pis.ws.ditec.sk", className = "sk.ditec.exp.rinfws.GetRinfDataServiceTuResponse")
    @Action(input = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceTuRequest", output = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceTuResponse", fault = {
        @FaultAction(className = AppException.class, value = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceTu:Fault:AppException")
    })
    public String getRinfDataServiceTu(
        @WebParam(name = "AuthInfoWS", targetNamespace = "")
        AuthInfoWS authInfoWS,
        @WebParam(name = "IdCskmdOdOpOd", targetNamespace = "")
        String idCskmdOdOpOd,
        @WebParam(name = "IdCskmdOdOpDo", targetNamespace = "")
        String idCskmdOdOpDo,
        @WebParam(name = "CisloTu", targetNamespace = "")
        String cisloTu)
        throws AppException
    ;

    /**
     * 
     * @param authInfoWS
     * @param cisloTu
     * @return
     *     returns java.lang.String
     * @throws AppException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRinfDataServiceTuKomplet", targetNamespace = "urn:rinf.pis.ws.ditec.sk", className = "sk.ditec.exp.rinfws.GetRinfDataServiceTuKomplet")
    @ResponseWrapper(localName = "getRinfDataServiceTuKompletResponse", targetNamespace = "urn:rinf.pis.ws.ditec.sk", className = "sk.ditec.exp.rinfws.GetRinfDataServiceTuKompletResponse")
    @Action(input = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceTuKompletRequest", output = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceTuKompletResponse", fault = {
        @FaultAction(className = AppException.class, value = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceTuKomplet:Fault:AppException")
    })
    public String getRinfDataServiceTuKomplet(
        @WebParam(name = "AuthInfoWS", targetNamespace = "")
        AuthInfoWS authInfoWS,
        @WebParam(name = "CisloTu", targetNamespace = "")
        String cisloTu)
        throws AppException
    ;

    /**
     * 
     * @param authInfoWS
     * @return
     *     returns java.lang.String
     * @throws AppException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRinfDataServiceKomplet", targetNamespace = "urn:rinf.pis.ws.ditec.sk", className = "sk.ditec.exp.rinfws.GetRinfDataServiceKomplet")
    @ResponseWrapper(localName = "getRinfDataServiceKompletResponse", targetNamespace = "urn:rinf.pis.ws.ditec.sk", className = "sk.ditec.exp.rinfws.GetRinfDataServiceKompletResponse")
    @Action(input = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceKompletRequest", output = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceKompletResponse", fault = {
        @FaultAction(className = AppException.class, value = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceKomplet:Fault:AppException")
    })
    public String getRinfDataServiceKomplet(
        @WebParam(name = "AuthInfoWS", targetNamespace = "")
        AuthInfoWS authInfoWS)
        throws AppException
    ;

    /**
     * 
     * @param op
     * @param authInfoWS
     * @return
     *     returns java.lang.String
     * @throws AppException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRinfDataServiceOp", targetNamespace = "urn:rinf.pis.ws.ditec.sk", className = "sk.ditec.exp.rinfws.GetRinfDataServiceOp")
    @ResponseWrapper(localName = "getRinfDataServiceOpResponse", targetNamespace = "urn:rinf.pis.ws.ditec.sk", className = "sk.ditec.exp.rinfws.GetRinfDataServiceOpResponse")
    @Action(input = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceOpRequest", output = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceOpResponse", fault = {
        @FaultAction(className = AppException.class, value = "urn:rinf.pis.ws.ditec.sk:RinfDataWS:getRinfDataServiceOp:Fault:AppException")
    })
    public String getRinfDataServiceOp(
        @WebParam(name = "AuthInfoWS", targetNamespace = "")
        AuthInfoWS authInfoWS,
        @WebParam(name = "Op", targetNamespace = "")
        String op)
        throws AppException
    ;

}
