torque.database.APP.adapter=oracle
torque.database.default = APP
torque.dsfactory.APP.factory=org.apache.torque.dsfactory.SharedPoolDataSourceFactory
torque.dsfactory.APP.pool.maxActive=60
torque.dsfactory.APP.pool.testOnBorrow=true
torque.dsfactory.APP.pool.validationQuery=SELECT sysdate from dual

torque.dsfactory.APP.connection.driver = net.sf.log4jdbc.DriverSpy

# ZSRDEV - CUD
#torque.dsfactory.APP.connection.url = jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = dev-oracle19.intra.ditec.sk)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = zsrdev.intra.ditec.sk)))
torque.dsfactory.APP.connection.url = jdbc:log4jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = dev-oracle19.intra.ditec.sk)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = zsrdev.intra.ditec.sk)))
torque.dsfactory.APP.connection.user = cud
torque.dsfactory.APP.connection.password = cud

# SSD - CUD
#torque.dsfactory.APP.connection.url = jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=kistest.intra.ditec.sk)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ssd.intra.ditec.sk)))
##torque.dsfactory.APP.connection.url = jdbc:log4jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=kistest.intra.ditec.sk)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ssd.intra.ditec.sk)))
#torque.dsfactory.APP.connection.user = cud
#torque.dsfactory.APP.connection.password = cud

# CUDT - CUD
###torque.dsfactory.APP.connection.url = jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=rhlkistdbcud)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=CUDT)))
#torque.dsfactory.APP.connection.url = jdbc:log4jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=rhlkistdbcud)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=CUDT)))
#torque.dsfactory.APP.connection.user = cud
#torque.dsfactory.APP.connection.password = CUD2022

# CUDP - CUD
##torque.dsfactory.APP.connection.url = jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=rhlkispdbcud)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=CUDP)))
#torque.dsfactory.APP.connection.url = jdbc:log4jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=rhlkispdbcud)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=CUDP)))
#torque.dsfactory.APP.connection.user = cud
#torque.dsfactory.APP.connection.password = RzMrmmrmK993


# PISP - VLAK
#torque.dsfactory.APP.connection.url = jdbc:log4jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=odbrpisp1)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=PISP)))
##torque.dsfactory.APP.directconnection.url = jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=odbrpisp1)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=PISP)))
#torque.dsfactory.APP.connection.user = vlak
#torque.dsfactory.APP.connection.password =ditec2012