
package sk.ditec.crd.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CRDDataReplicationPort", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRDDataReplicationPort {


    /**
     * 
     * @param countryReplicationRequest
     * @return
     *     returns sk.ditec.crd.ws.CountryReplicationResponse
     */
    @WebMethod(operationName = "CountryReplication")
    @WebResult(name = "CountryReplicationResponse", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", partName = "CountryReplicationResponse")
    public CountryReplicationResponse countryReplication(
        @WebParam(name = "CountryReplicationRequest", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", partName = "CountryReplicationRequest")
        CountryReplicationRequest countryReplicationRequest);

    /**
     * 
     * @param companyReplicationRequest
     * @return
     *     returns sk.ditec.crd.ws.CompanyReplicationResponse
     */
    @WebMethod(operationName = "CompanyReplication")
    @WebResult(name = "CompanyReplicationResponse", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", partName = "CompanyReplicationResponse")
    public CompanyReplicationResponse companyReplication(
        @WebParam(name = "CompanyReplicationRequest", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", partName = "CompanyReplicationRequest")
        CompanyReplicationRequest companyReplicationRequest);

    /**
     * 
     * @param primaryLocationReplicationRequest
     * @return
     *     returns sk.ditec.crd.ws.PrimaryLocationReplicationResponse
     */
    @WebMethod(operationName = "PrimaryLocationReplication")
    @WebResult(name = "PrimaryLocationReplicationResponse", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", partName = "PrimaryLocationReplicationResponse")
    public PrimaryLocationReplicationResponse primaryLocationReplication(
        @WebParam(name = "PrimaryLocationReplicationRequest", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", partName = "PrimaryLocationReplicationRequest")
        PrimaryLocationReplicationRequest primaryLocationReplicationRequest);

    /**
     * 
     * @param subsidiaryLocationReplicationRequest
     * @return
     *     returns sk.ditec.crd.ws.SubsidiaryLocationReplicationResponse
     */
    @WebMethod(operationName = "SubsidiaryLocationReplication")
    @WebResult(name = "SubsidiaryLocationReplicationResponse", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", partName = "SubsidiaryLocationReplicationResponse")
    public SubsidiaryLocationReplicationResponse subsidiaryLocationReplication(
        @WebParam(name = "SubsidiaryLocationReplicationRequest", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", partName = "SubsidiaryLocationReplicationRequest")
        SubsidiaryLocationReplicationRequest subsidiaryLocationReplicationRequest);

    /**
     * 
     * @param subsidiaryTypeReplicationRequest
     * @return
     *     returns sk.ditec.crd.ws.SubsidiaryTypeReplicationResponse
     */
    @WebMethod(operationName = "SubsidiaryTypeReplication")
    @WebResult(name = "SubsidiaryTypeReplicationResponse", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", partName = "SubsidiaryTypeReplicationResponse")
    public SubsidiaryTypeReplicationResponse subsidiaryTypeReplication(
        @WebParam(name = "SubsidiaryTypeReplicationRequest", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", partName = "SubsidiaryTypeReplicationRequest")
        SubsidiaryTypeReplicationRequest subsidiaryTypeReplicationRequest);

}
