
package sk.ditec.crd.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CRDDataReplicationPortService", targetNamespace = "http://schema.refdata.li.cc.uic.org/types/v1", wsdlLocation = "http://a01service-zsr-ipaas.apps.ocptest.intra.zsr.sk/service/a01service?wsdl")
public class CRDDataReplicationPortService
    extends Service
{

    private final static URL CRDDATAREPLICATIONPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CRDDATAREPLICATIONPORTSERVICE_EXCEPTION;
    private final static QName CRDDATAREPLICATIONPORTSERVICE_QNAME = new QName("http://schema.refdata.li.cc.uic.org/types/v1", "CRDDataReplicationPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://a01service-zsr-ipaas.apps.ocptest.intra.zsr.sk/service/a01service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRDDATAREPLICATIONPORTSERVICE_WSDL_LOCATION = url;
        CRDDATAREPLICATIONPORTSERVICE_EXCEPTION = e;
    }

    public CRDDataReplicationPortService() {
        super(__getWsdlLocation(), CRDDATAREPLICATIONPORTSERVICE_QNAME);
    }

    public CRDDataReplicationPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRDDATAREPLICATIONPORTSERVICE_QNAME, features);
    }

    public CRDDataReplicationPortService(URL wsdlLocation) {
        super(wsdlLocation, CRDDATAREPLICATIONPORTSERVICE_QNAME);
    }

    public CRDDataReplicationPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRDDATAREPLICATIONPORTSERVICE_QNAME, features);
    }

    public CRDDataReplicationPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CRDDataReplicationPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CRDDataReplicationPort
     */
    @WebEndpoint(name = "CRDDataReplicationPortSoap11")
    public CRDDataReplicationPort getCRDDataReplicationPortSoap11() {
        return super.getPort(new QName("http://schema.refdata.li.cc.uic.org/types/v1", "CRDDataReplicationPortSoap11"), CRDDataReplicationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRDDataReplicationPort
     */
    @WebEndpoint(name = "CRDDataReplicationPortSoap11")
    public CRDDataReplicationPort getCRDDataReplicationPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://schema.refdata.li.cc.uic.org/types/v1", "CRDDataReplicationPortSoap11"), CRDDataReplicationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRDDATAREPLICATIONPORTSERVICE_EXCEPTION!= null) {
            throw CRDDATAREPLICATIONPORTSERVICE_EXCEPTION;
        }
        return CRDDATAREPLICATIONPORTSERVICE_WSDL_LOCATION;
    }

}
